### ISSUE TITLE
replace email template with web form

### ISSUE THREAD

**Issue by whysthatso** [osarrouy/robinhoodcoop#20]
Instead of email request that leads to app we would like to have a pre-filled webform with same info from Fortmatic: firstname; last name; ETH Address and email
additionally:

- Add (Empty) field for email (in case person used phone on Fortmatic)
- Add Empty field for Phone number (including international code)
- Add Empty field for Address of Residence
- Add check box to accept terms (Terms are a link to a modal including the text > editable in the git repo of the app) 

Button to Submit: when press the app sends  an email with all info to registration@robinhoodcoop.org as before. 

After click “submit” button a pop up message should inform the user:

“Your account needs to be activated by an admin. Robin Hood coop will send you an email as soon as your account is ready for log in. Keep an eye on your inbox (and spam folder too). “

This email could contain “continue to log in” button

**Comment by osarrouy** [comment]
Empty phone field
