### ISSUE TITLE
please check phone number verification

### ISSUE THREAD

**Issue by whysthatso** [osarrouy/robinhoodcoop#32]
we have a member complaining that entering valid phone numbers is not accepted by the form, see screenshot example
<img width="413" alt="Screenshot 2020-09-16 at 04 02 07 AM" src="https://user-images.githubusercontent.com/1685114/93294439-2b12fe00-f7f3-11ea-8f12-fffdbe2e0eff.png">

can you have a look, and possibly make the verification more forgiving?

**Comment by whysthatso** [comment]
another member confirmed my suspicion:

>  I immediately wanted to sign up but came across an issue: my telephone number seems to be too long, according to the signup form (I checked the validation regex code of the signup form and it seems that the maximum accepted length of a phone number is 13 digits including the country code, area code and subscriber number, but international standard should be 15 digits ); should be an easy and quick fix for the programmer.

**Comment by whysthatso** [comment]
i would even leave this number to be higher, no need to be that strict.

**Comment by whysthatso** [comment]
reopen for review

**Comment by osarrouy** [comment]
Your fix all looks good to me. You didn't have any issue since ?

**Comment by osarrouy** [comment]
Looks good so closing it.
