### ISSUE TITLE
in terms modal, explicitly style text black and background black 

### ISSUE THREAD

**Issue by whysthatso** [osarrouy/robinhoodcoop#34]
we have reports of people telling us that in some browsers the text appears as white

got one specific feedback:

> Separately, the terms and conditions box opens up looking blank (this is on Safari, Brave and Firefox) but it is actually white text on white background, so you have to copy and paste it to a separate document to view the text. If the text could be turned to black, that would be great.

**Comment by whysthatso** [comment]
reopen for review

**Comment by osarrouy** [comment]
Fixed by d580d2d.
