### ISSUE TITLE
not sending emails while registrating new members

### ISSUE THREAD

**Issue by whysthatso** [osarrouy/robinhoodcoop#35]
at the moment, it seems that there is a bug somewhere in the check of the transaction state.

when i submit the transaction the metamask plugin takes over, and all is well. at the same time i get this error in the console:

```
index.mjs:629 Uncaught (in promise) Error: Function called outside component initialization
    at K (index.mjs:629)
    at X (index.mjs:662)
    at Pt (context.js:10)
    at nr (notifications.js:27)
    at et.<anonymous> (Create.svelte:69)

```

  | K | @ | index.mjs:629
-- | -- | -- | --
  | X | @ | index.mjs:662
  | Pt | @ | context.js:10
  | nr | @ | notifications.js:27
  | (anonymous) | @ | Create.svelte:69
  | async function (async) |   |  
  | (anonymous) | @ | Create.svelte:56
  | (anonymous) | @ | index.mjs:653
  | (anonymous) | @ | index.mjs:652
  | (anonymous) | @ | Form.svelte:10
  | (anonymous) | @ | index.mjs:238

**Comment by whysthatso** [comment]
this might be related
https://github.com/sveltejs/sapper/issues/592

**Comment by osarrouy** [comment]
I could not reproduce this issue. It worked both on Brave and Metamask. Questions:

1. Which browser are you using ?
2. Does this happen all the time ?
2. Did the transaction succeeded or failed in the end ? Cause the line the errors points to is about error handling - if the transaction did fail it's a normal behavior that the user received no mail. The Ethereum is quite clogged these days so a lot of transactions fail and there is not much we can do about it ...

**Comment by whysthatso** [comment]
![Screenshot-20201012100630-1712x936](https://user-images.githubusercontent.com/1685114/95715593-c96b7580-0c72-11eb-89a4-d91bfaba7d4b.png)

happens both on
chrome 86.0.4240.75 (Official Build) (64-bit)
firefox 81.0.1 (64-bit)

error appears as soon as i click the Confirm in the metamask extension. 

happens reproducibly all the time.

happens with short running/immediate and long running transactions (browser open for 1-2 hours). i played around a bit with different gas prices, there have been no failed transactions, not sure such a thing even exists. (i'm not aware of a hard limit after which network nodes would drop unconfirmed transactions, i guess that depends on the node's client software?)

problem still exists.

**Comment by whysthatso** [comment]
![Screenshot-20201012102814-1712x936](https://user-images.githubusercontent.com/1685114/95717480-ad1d0800-0c75-11eb-9407-5de8e8904b49.png)
by chance i just rejected a transaction, and i get exactly the same error. this does not seem to be related to the state of the transaction at all.
